# Generated by Django 5.0.14 on 2026-06-19 00:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_meters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_settings', to='core.business')),
                ('location', models.ForeignKey(blank=True, help_text='Optional. Null applies business-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_settings', to='core.businesslocation')),
            ],
            options={
                'ordering': ['business', 'location'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked in'), ('clocked_out', 'Clocked out')], default='clocked_in', max_length=16)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clock_out_distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clock_in_within_geofence', models.BooleanField(blank=True, null=True)),
                ('clock_out_within_geofence', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.businessmembership')),
            ],
            options={
                'ordering': ['-clock_in_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('clock_in', 'Clock in'), ('clock_out', 'Clock out')], max_length=16)),
                ('reported_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reported_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('within_geofence', models.BooleanField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence_setting', models.ForeignKey(blank=True, help_text='Which setting was evaluated, if any. Null if no geofence applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='employees.geofencesetting')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_verification_logs', to='core.businessmembership')),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='employees.timeentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntryBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_start_at', models.DateTimeField()),
                ('break_end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='employees.timeentry')),
            ],
            options={
                'ordering': ['-break_start_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='geofencesetting',
            constraint=models.UniqueConstraint(fields=('business', 'location'), name='unique_geofence_per_business_location'),
        ),
        migrations.AddConstraint(
            model_name='geofencesetting',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('business',), name='unique_geofence_per_business_when_business_wide'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_out_at__isnull', True)), fields=('membership',), name='unique_open_time_entry_per_membership'),
        ),
        migrations.AddConstraint(
            model_name='timeentrybreak',
            constraint=models.UniqueConstraint(condition=models.Q(('break_end_at__isnull', True)), fields=('time_entry',), name='unique_open_break_per_time_entry'),
        ),
    ]
