# Generated by Django 5.0.14 on 2026-06-19 01:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.businessmembership')),
            ],
            options={
                'ordering': ['membership', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.business')),
            ],
            options={
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayStub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_stubs', to='core.businessmembership')),
                ('position', models.ForeignKey(help_text="Which Position's hourly_rate this pay stub was calculated from.", on_delete=django.db.models.deletion.PROTECT, related_name='pay_stubs', to='employees.position')),
            ],
            options={
                'ordering': ['-pay_period_start'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_rule', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null means ongoing, no end date.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Pausing this stops future expansion without deleting history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='core.businessmembership')),
            ],
            options={
                'ordering': ['membership', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.businessmembership')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='employees.position')),
                ('recurring_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_shifts', to='employees.recurringschedule')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_swaps_approved', to='core.businessmembership')),
                ('requesting_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_swap_requests_made', to='core.businessmembership')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='employees.employeeshift')),
                ('target_membership', models.ForeignKey(blank=True, help_text='Who the requester wants to swap with. Null means an open request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_swap_requests_targeted', to='core.businessmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(help_text='If <= start_time, the shift is treated as crossing midnight.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.business')),
                ('location', models.ForeignKey(blank=True, help_text='Optional. Null applies business-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.businesslocation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_templates', to='employees.position')),
            ],
            options={
                'ordering': ['business', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='employees.shifttemplate'),
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_off_approvals', to='core.businessmembership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='core.businessmembership')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_position_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='paystub',
            constraint=models.UniqueConstraint(fields=('membership', 'pay_period_start', 'pay_period_end'), name='unique_pay_stub_per_membership_period'),
        ),
        migrations.AddConstraint(
            model_name='employeeshift',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_schedule__isnull', False)), fields=('recurring_schedule', 'start_at'), name='unique_shift_per_recurring_schedule_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='timeoffrequest',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='time_off_end_date_after_start_date'),
        ),
    ]
