# Generated by Django 5.0.14 on 2026-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeavailability_position_paystub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='auto_closed_on_deactivation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeentrybreak',
            name='auto_closed_on_deactivation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
