# Generated by Django 5.2.15 on 2026-06-18 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_legacy', models.BooleanField(default=False, help_text='Grandfathered accounts that never expire regardless of trial/subscription status.')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expired', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(blank=True, default='', help_text='Mirrors the Stripe subscription status string (trialing, active, past_due, canceled, ...).', max_length=32)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('hours', models.JSONField(blank=True, default=dict, help_text="Per-day open/close times, replacing the old business_hours table's one-row-per-day-of-week pattern. Exact shape to be finalized when the Reservations domain is built.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.business')),
                ('location', models.ForeignKey(blank=True, help_text='Optional. Scopes a staff member to a single location; null means business-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.businesslocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business', 'role'],
                'constraints': [models.UniqueConstraint(fields=('business', 'user'), name='unique_membership_per_business')],
            },
        ),
    ]
