# Generated by Django 5.0.14 on 2026-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='tax_type',
            field=models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_type',
            field=models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='default_tax_type',
            field=models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16),
        ),
    ]
