# Generated by Django 5.0.14 on 2026-06-19 23:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('finance', '0002_alter_estimate_tax_type_alter_invoice_tax_type_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recurring_occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for a credit, negative for a debit.', max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=16)),
                ('external_transaction_id', models.CharField(blank=True, default='', help_text='Set by a future bank-feed import; always blank for manual entry.', max_length=255)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='core.business')),
                ('reconciled_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurring_occurrence_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(editable=False, max_length=32)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='none', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_type', models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.business')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='finance.chartofaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.bill')),
            ],
            options={
                'ordering': ['bill', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BillNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_number_sequence', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('other', 'Other')], max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='finance.bill')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_bill_payments', to='core.businessmembership')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Which account the money was paid from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='finance.chartofaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill')], max_length=16)),
                ('line_item_presets', models.JSONField(blank=True, default=list, help_text='[{"description": ..., "quantity": ..., "unit_price": ...}, ...]')),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='none', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_type', models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('due_in_days', models.PositiveIntegerField(default=30, help_text="Generated document's due_date = occurrence date + this many days.")),
                ('recurrence_rule', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null means ongoing, no end date.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Pausing this stops future expansion without deleting history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='core.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='customers.customer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='inventory.vendor')),
            ],
            options={
                'ordering': ['business', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='finance.recurringtransaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='finance.recurringtransaction'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_transaction__isnull', False)), fields=('recurring_transaction', 'recurring_occurrence_date'), name='unique_invoice_per_recurring_transaction_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_id', ''), _negated=True), fields=('business', 'external_transaction_id'), name='unique_bank_transaction_external_id_per_business'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('business', 'bill_number'), name='unique_bill_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_transaction__isnull', False)), fields=('recurring_transaction', 'recurring_occurrence_date'), name='unique_bill_per_recurring_transaction_occurrence'),
        ),
    ]
