# Generated by Django 5.0.14 on 2026-06-20 02:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='core.business')),
                ('purchaser_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gift_cards', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('initial', 'Initial balance'), ('reload', 'Reload'), ('redemption', 'Redemption')], max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='core.businessmembership')),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.giftcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('silver_threshold', models.PositiveIntegerField(default=500, help_text='Lifetime points required to reach Silver.')),
                ('gold_threshold', models.PositiveIntegerField(default=2000, help_text='Lifetime points required to reach Gold.')),
                ('platinum_threshold', models.PositiveIntegerField(default=5000, help_text='Lifetime points required to reach Platinum.')),
                ('points_expire_after_days', models.PositiveIntegerField(blank=True, help_text='Null (default) means points never expire.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='core.business')),
            ],
            options={
                'ordering': ['business', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('current_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='customers.customer')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='loyalty.loyaltyprogram')),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='none', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_type', models.CharField(choices=[('ZERO', 'No Tax (0%)'), ('GST_5', 'GST (5%)'), ('HST_15', 'HST (15%)'), ('GST_QST_14975', 'GST + QST (14.975%)'), ('QST_9975', 'QST (9.975%)')], default='ZERO', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='loyalty.order')),
            ],
            options={
                'ordering': ['order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('order', 'Order'), ('redemption', 'Redemption'), ('manual', 'Manual adjustment'), ('expiration', 'Expiration'), ('reversal', 'Reversal')], max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Set only on earn transactions, when the program defines an expiration window.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='loyalty.customerloyaltyaccount')),
                ('expired_transaction', models.ForeignKey(blank=True, help_text='Set only on a compensating EXPIRATION transaction — points at the earn transaction it expires.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiration_compensations', to='loyalty.pointstransaction')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='loyalty.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loyaltyprogram',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_loyalty_program_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='customerloyaltyaccount',
            constraint=models.UniqueConstraint(fields=('customer', 'loyalty_program'), name='unique_account_per_customer_program'),
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('expired_transaction__isnull', False)), fields=('expired_transaction',), name='unique_expiration_per_transaction'),
        ),
    ]
