# Generated by Django 5.0.14 on 2026-06-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyaltyaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_accounts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerloyaltyaccount',
            name='loyalty_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='loyalty.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.giftcard'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_transactions', to='loyalty.customerloyaltyaccount'),
        ),
    ]
