# Generated by Django 5.0.14 on 2026-06-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_invoice_status_refund'),
        ('loyalty', '0002_alter_customerloyaltyaccount_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='finance.invoice'),
        ),
    ]
