# Generated by Django 5.0.14 on 2026-06-19 02:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='core.businesslocation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='core.businesslocation')),
            ],
            options={
                'ordering': ['location', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Main', max_length=255)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='e.g. {"tables": [{"table_id": "<uuid>", "rotation": 0}], "elements": [...]}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='core.businesslocation')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_duration_minutes', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Minimum gap enforced between two reservations on the same table.')),
                ('min_advance_minutes', models.PositiveIntegerField(default=0, help_text='How last-minute a guest booking may be made.')),
                ('max_advance_days', models.PositiveIntegerField(default=60, help_text='How far in advance a guest may book.')),
                ('max_party_size', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_setting', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.businesslocation')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=32)),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Resolved and stored by save() if not given: ReservationSetting.default_duration_minutes, or 90.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='pending', max_length=16)),
                ('confirmation_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.businesslocation')),
                ('table', models.ForeignKey(blank=True, help_text='Null until a table is assigned (by the booking service, or manually by staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.restauranttable')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=32)),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('requested_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('seated', 'Seated'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.businesslocation')),
                ('reservation', models.OneToOneField(blank=True, help_text='Set when staff convert this waitlist entry into a real Reservation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='reservations.reservation')),
            ],
            options={
                'ordering': ['requested_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='blackoutdate',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_blackout_per_location_date'),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.UniqueConstraint(fields=('location', 'day_of_week'), name='unique_hours_per_location_day'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_table_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='reservation_end_after_start'),
        ),
    ]
