# Generated by Django 5.0.14 on 2026-06-19 14:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must contain 7-15 digits, optionally prefixed with '+'.", regex='^\\+?[0-9]{7,15}$')])),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('email_on_new_reservation', models.BooleanField(default=True)),
                ('email_on_low_stock', models.BooleanField(default=True)),
                ('email_on_new_lead', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.business')),
                ('logo', models.ForeignKey(blank=True, help_text='Set via the upload-logo action (settings/services.py:set_logo), never written directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
            ],
        ),
    ]
